version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: autoresDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=autoresDB;Username=postgres;Password=postgres
    depends_on:
      - postgres
volumes:
  pgdata: